name: asilplanner
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Bu daha stabil bir ifade olur, dev sürüm yerine

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/flor.svg
    - lib/assets/icons/whatsapp_1.svg
    - lib/assets/icons/instagram.svg
    - lib/assets/icons/social-media.svg
    - lib/assets/icons/youtube.svg
    - lib/assets/icons/call.svg
    - lib/assets/icons/camera.svg
    - lib/assets/icons/clouds.svg
    - lib/assets/icons/mail.svg
    - lib/assets/icons/sound.svg

  fonts:
    - family: italian
      fonts:
        - asset: lib/assets/fonts/Italiana,Raleway/Italiana/Italiana-Regular.ttf
